"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let num = 24;
let num2 = 35;
console.log(num + num2);
console.log("hello");
let str = "madhav";
let arr = [1, "madhav", 523, "this is a string"];
console.log(arr);
console.log(arr.length);
